tls:
  certificates:
    - certFile: /certs/fullchain_wildcard.complexsimplicityai.com.pem
      keyFile: /certs/wildcard.complexsimplicityai.com.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/fullchain_wildcard.complexsimplicityai.com.pem
        keyFile: /certs/wildcard.complexsimplicityai.com.key
