http:
  middlewares:
    jwt-auth:
      plugin:
        jwt:
          required: true
          payloadFields:
            - exp
          jwtHeaders:
            X-JWT-Subject: sub
            X-JWT-Email: email
            X-JWT-Name: name
          keys:
            - e3402c23868d4ec18289f0052ab71b91

    sablier-scale:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          group: default
          sessionDuration: 5m
          dynamic:
            displayName: Wolf Services
            theme: hacker-terminal
            refreshFrequency: 5s
