http:
  routers:
    landing-page:
      entryPoints:
        - https
      rule: "Host(`complexsimplicityai.com`) || Host(`www.complexsimplicityai.com`)"
      service: "landing-page-service"
      middlewares:
        - "landing-page-static"
      tls:
        # Use default wildcard certs defined in certificates.yml
        {}

  services:
    landing-page-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1" # Dummy URL, plugin handles the request

  middlewares:
    landing-page-static:
      plugin:
        static-server:
          root: "/www"
